In [1]:
from sklearn.datasets import fetch_20newsgroups                

In [2]:
train_data=fetch_20newsgroups(subset='train')

In [3]:
train_data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [4]:
categories_chosen=['alt.atheism','comp.graphics','rec.autos','rec.motorcycles','sci.electronics']
train=fetch_20newsgroups(subset='train',categories=categories_chosen)
test=fetch_20newsgroups(subset='test',categories=categories_chosen)

In [5]:
train

{'data': ["From: jam@ameslab.gov (Jerry Musselman)\nSubject: UART needed\nOrganization: Ames Laboratory, ISU\nLines: 9\n\nI need to find a UART that will interface to an 8051 and do the following:\n\t-250k baud, 8 data bits, 2 stop bits, no parity\n\t-ability to do BREAK detect (IRQ or output pin)\n\t-IRQ on character received\n\nI'm using a Dallas DS2250 at 16 Mhz (8051 clone), but it won't do \nbreak detect.  I've looked at the 6850, 8251, 7201, 2661, etc...\n\n\tAny help would be appriciated!!!\n",
  "From: ph@gmd.de (Peter Hendricks)\nSubject: Re: Wanted: A to D hardware for a PC\nTo: ebuddington@eagle.wesleyan.edu\nNntp-Posting-Host: gmdzi\nOrganization: GMD, Sankt Augustin, Germany\nLines: 23\n\nIn <3889@ncr-mpd.FtCollinsCO.NCR.COM> Brad Wright writes:\n\n>\tIf you know much about PC's (IBM comp) you might try the joystick\n>port.  Though I haven't tried this myself, I've been told that the port\n>has built in A-D converters.  This would allow the joystick to be a couple of \n>po

In [6]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [7]:
text_clf=Pipeline([('vect',TfidfVectorizer()),('clf',MultinomialNB())])

In [8]:
text_clf.fit(train.data,train.target)

Pipeline(steps=[('vect', TfidfVectorizer()), ('clf', MultinomialNB())])

In [9]:
predicted=text_clf.predict(test.data)

In [10]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
import numpy as np


In [11]:
print("Accuracy:" +str(np.mean(predicted==test.target)))

Accuracy:0.9150395778364117


In [12]:
print(metrics.classification_report(test.target,predicted,target_names=test.target_names),metrics.confusion_matrix(test.target,predicted))

                 precision    recall  f1-score   support

    alt.atheism       0.97      0.96      0.97       319
  comp.graphics       0.94      0.86      0.90       389
      rec.autos       0.83      0.97      0.90       396
rec.motorcycles       0.93      0.96      0.95       398
sci.electronics       0.93      0.82      0.87       393

       accuracy                           0.92      1895
      macro avg       0.92      0.92      0.92      1895
   weighted avg       0.92      0.92      0.91      1895
 [[307   2   4   4   2]
 [  7 335  21   5  21]
 [  0   2 386   5   3]
 [  0   0  16 382   0]
 [  2  17  36  14 324]]
